CREATE DATABASE vino
    DEFAULT CHARACTER SET utf8;

USE vino;

CREATE TABLE tabla_banner (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	imagen LONGBLOB NOT NULL UNIQUE
);