CREATE DATABASE vino
    DEFAULT CHARACTER SET utf8;

USE vino;

CREATE TABLE tabla_banner (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	imagen LONGBLOB NOT NULL UNIQUE
);

CREATE TABLE tabla_vino_tinto (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	imagen LONGBLOB NOT NULL UNIQUE,
	descripcion VARCHAR(250) NOT NULL,
	precio VARCHAR(20) NOT NULL
);

CREATE TABLE tabla_vino_blanco (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	imagen LONGBLOB NOT NULL UNIQUE,
	descripcion VARCHAR(250) NOT NULL,
	precio VARCHAR(20) NOT NULL
);

CREATE TABLE tabla_vino_rosa (
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	imagen LONGBLOB NOT NULL UNIQUE,
	descripcion VARCHAR(250) NOT NULL,
	precio VARCHAR(20) NOT NULL
);